
import { Area } from './types';

export const CHECKLIST_TEMPLATES: Record<Area, string[]> = {
  [Area.DFP2]: [
    'SECTION:PARÂMETROS OPERACIONAIS',
    'Ply (Tipo)',
    'Linhas em alimentação (1-4)',
    'Taxa (tph)',
    'Vazão de diluição (m³/h)',
    'SECTION:CÉLULAS DE FLOTAÇÃO',
    'SECTION:SUBCÉLULA M1',
    'Nível (%)',
    'Setpoint (%)',
    'SECTION:COLECTOR',
    'Vazão (L/min)',
    'SP (L/min)',
    'SECTION:FROTHER',
    'Vazão (L/min)',
    'SP (L/min)',
    'Velocidade da bomba (Hz)',
    'Nota',
    'SECTION:SUBCÉLULA M2',
    'Nível (%)',
    'Setpoint (%)',
    'SECTION:COLECTOR',
    'Vazão (L/min)',
    'SP (L/min)',
    'SECTION:FROTHER',
    'Vazão (L/min)',
    'SP (L/min)',
    'Velocidade da bomba (Hz)',
    'Nota',
    'SECTION:SUBCÉLULA M3',
    'Nível (%)',
    'Setpoint (%)',
    'SECTION:COLECTOR',
    'Vazão (L/min)',
    'SP (L/min)',
    'SECTION:FROTHER',
    'Vazão (L/min)',
    'SP (L/min)',
    'Velocidade da bomba (Hz)',
    'Nota',
    'SECTION:SUBCÉLULA M4',
    'Nível (%)',
    'Setpoint (%)',
    'SECTION:COLECTOR',
    'Vazão (L/min)',
    'SP (L/min)',
    'SECTION:FROTHER',
    'Vazão (L/min)',
    'SP (L/min)',
    'Velocidade da bomba (Hz)',
    'Nota',
    'SECTION:NÍVEIS DO TANK DE REAGENTE',
    'Collector Reagente (%)',
    'Frother Reagente (%)',
    'SECTION:EQUIPAMENTOS LADO C',
    'SECTION:Sieve Bends - LADO C',
    '7C SV 101',
    '7C SV 201',
    '7C SV 301',
    '7C SV 401',
    'SECTION:flotation feed pps - LADO C',
    '7C PP 118',
    '7C PP 119',
    'SECTION:flotation circulating pps - LADO C',
    '6C CP 101',
    '6C CP 102',
    '6C CP 103',
    '6C CP 104',
    '6C CP 105',
    '6C CP 201',
    '6C CP 202',
    '6C CP 203',
    '6C CP 204',
    '6C CP 205',
    'SECTION:Flotation conc. pp - LADO C',
    '6C PP 108',
    'SECTION:Flotation tailing pp - LADO C',
    '7C PP 120',
    'SECTION:EQUIPAMENTOS LADO D',
    'SECTION:Sieve Bends - LADO D',
    '7D SV 101',
    '7D SV 201',
    '7D SV 301',
    '7D SV 401',
    'SECTION:flotation feed pps - LADO D',
    '7D PP 118',
    '7D PP 119',
    'SECTION:flotation circulating pps - LADO D',
    '6D CP 101',
    '6D CP 102',
    '6D CP 103',
    '6D CP 104',
    '6D CP 105',
    '6D CP 201',
    '6D CP 202',
    '6D CP 203',
    '6D CP 204',
    '6D CP 205',
    'SECTION:Flotation conc. pp - LADO D',
    '6D PP 108',
    'SECTION:Flotation tailing pp - LADO D',
    '7D Recirculation pp',
    '7D PP 120',
    'SECTION:OUTROS SISTEMAS',
    '7C PP 130 (Spillage pp)',
    'Nota Geral',
  ],
  [Area.BOMBEAMENTO]: [
    'SECTION:VACUUM PUMPS – PLANTA C',
    '06C-VP-101',
    '06C-VP-201',
    '06C-VP-301',
    '06C-VP-401',
    '06C-VP-501',
    'SECTION:VACUUM PUMPS – PLANTA D',
    '06D-VP-101',
    '06D-VP-201',
    '06D-VP-301',
    '06D-VP-401',
    '06D-VP-501',
    'SECTION:FILTRATE PUMPS – PLANTA C',
    '06C-PP-104',
    '06C-PP-105',
    '06C-PP-204',
    '06C-PP-205',
    '06C-PP-304',
    '06C-PP-305',
    'SECTION:FILTRATE PUMPS – PLANTA D',
    '06D-PP-104',
    '06D-PP-105',
    '06D-PP-204',
    '06D-PP-205',
    '06D-PP-304',
    '06D-PP-305',
    'SECTION:BOMBAS ESPESSADOR 101 C',
    '7C-PP-101',
    '7C-PP-102',
    'SECTION:BOMBAS ESPESSADOR 101 D',
    '7D-PP-101',
    '7D-PP-102',
    'SECTION:BOMBAS ESPESSADOR 102',
    '7C-PP-107',
    '7C-PP-108',
    '9C-PP-120',
    '9C-PP-128',
    'SECTION:BOMBAS ESPESSADOR 103',
    '7C-PP-109',
    '7C-PP-110',
    '9C-PP-112',
    '9C-PP-113',
    '9C-PP-114',
    '9C-PP-121',
    '9C-PP-122',
    '9C-PP-123',
    'SECTION:BOMBAS BUFAS TANK',
    '7C-PP-111',
    '7C-PP-112',
    '7C-PP-113',
    'SECTION:BOMBAS TANK 104',
    '6C-PP-107',
    '6C-PP-207',
    '6C-PP-307',
    'SECTION:BOMBAS SLIMES',
    '7D-PP-107',
    '7D-PP-104',
    '7D-PP-111',
    '7D-PP-108',
    'SECTION:BOMBAS CLARIFIED C',
    '9C-PP-101',
    '9C-PP-102',
    '9C-PP-103',
    '9C-PP-104',
    '9C-PP-105',
    '9C-PP-106',
    'SECTION:BOMBAS CLARIFIED D',
    '9D-PP-101',
    '9D-PP-102',
    '9D-PP-103',
    '9D-PP-104',
    '9D-PP-105',
    '9D-PP-106',
    'SECTION:BOMBAS COLUMN WASH',
    '6C-PP-103',
    '6D-PP-103',
    'SECTION:BOMBAS FLOTATION FEED',
    '5C-PP-101',
    '5D-PP-101',
    'SECTION:BOMBAS CLOTH WASH',
    '6C-PP-201',
    '6D-PP-201',
    'SECTION:BOMBAS CONCENTRADO C',
    '6C-PP-102',
    '6C-PP-202',
    '6C-PP-302',
    'SECTION:BOMBAS CONCENTRADO D',
    '6D-PP-102',
    '6D-PP-202',
    '6D-PP-302',
    'SECTION:SPILLAGE PUMPS',
    '6C-PP-210',
    '6C-PP-211',
    '6C-PP-212',
    '7C-PP-114',
    '6C-PP-106',
    '6D-PP-210',
    '6D-PP-211',
    '6D-PP-212',
    '7D-PP-109',
    '7D-PP-108',
    '9D-PP-106',
    'SECTION:BOMBAS CLEAN WATER C',
    '9C-PP-107',
    '9C-PP-109',
    '9C-PP-110',
    '9C-PP-117',
    'SECTION:BOMBAS CLEAN WATER D',
    '9D-PP-107',
    '9D-PP-109',
    '9D-PP-110',
    '9D-PP-117',
    'SECTION:BOMBAS SUMPAO',
    '9C-PP-124',
    '9C-PP-125',
    '9C-PP-126',
    '9C-PP-127'
  ],
  [Area.ESPESADORES]: [
    'SECTION:7C TH 101',
    'Rakes 101C',
    'Torque 101C (%)',
    'Altura rake 101C (mm)',
    'Densidade Setpoint 101C (t/m³)',
    'Densidade Actual 101C (t/m³)',
    'Qualidade Água 101C',
    'Fluxo Floculante 101C (l/min)',
    'SECTION:7D TH 101',
    'Rakes 101D',
    'Torque 101D (%)',
    'Altura rake 101D (mm)',
    'Densidade Setpoint 101D (t/m³)',
    'Densidade Actual 101D (t/m³)',
    'Qualidade Água 101D',
    'Fluxo Floculante 101D (l/min)',
    'SECTION:7C TH 102',
    'Rakes 102',
    'Torque 102 (%)',
    'Altura rake 102 (mm)',
    'Densidade Setpoint 102 (t/m³)',
    'Densidade Actual 102 (t/m³)',
    'Qualidade Água 102',
    'Água de Diluição 102 (m³/h)',
    'Fluxo Floculante 102 (m³/h)',
    'SECTION:7C TH 103',
    'Rakes 103',
    'Torque 103 (%)',
    'Altura rake 103 (mm)',
    'Densidade Setpoint 103 (t/m³)',
    'Densidade Actual 103 (t/m³)',
    'Qualidade Água 103',
    'Água de Diluição 103 (m³/h)',
    'Fluxo Floculante 103 (m³/h)',
    'SECTION:NÍVEIS DOS TANKS',
    'Tank 1 (9C-FL-601F) (%)',
    'Tank 2 (9C-FL-601G) (%)',
    'Tank 3 (9C-FL-601N) (%)',
    'SECTION:DOSAGEM DE FLOCULANTE (g/t)',
    '7C TH 101 (g/t)',
    '7D TH 101 (g/t)',
    '7C TH 102 (g/t)',
    '7C TH 103 (g/t)'
  ],
  [Area.HBF_D]: [
    'SECTION:OPERAÇÃO HBF',
    'Feed rate HBF (m³/h)',
    'Pressão negativa (Kpa)',
    'SECTION:OPERAÇÃO COLUNAS',
    'ALIMENTANDO COLUNAS?',
    'Feed rate Colunas (m³/h)',
    'SECTION:COLECTOR',
    'Vazão (L/min)',
    'SP (L/min)',
    'SECTION:FROTHER',
    'Vazão (L/min)',
    'SP (L/min)',
    'SECTION:FLOTATION COLUMNS',
    '6D-FC-101',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    '6D-FC-102',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    '6D-FC-201',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    '6D-FC-202',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    '6D-FC-301',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    '6D-FC-302',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    'SECTION:EQUIPAMENTOS HBF',
    '6D-VF-101',
    '- Sprays',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6D-VF-201',
    '- Sprays',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6D-VF-301',
    '- Sprays',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    'SECTION:VELOCIDADES DOS BELTS',
    'Velocidade 101 (%)',
    'Velocidade 201 (%)',
    'Velocidade 301 (%)',
    'SECTION:SISTEMAS AUXILIARES',
    'Retorno do tanque 104',
    'VALVULA DE DILUICAO',
    'CORSE SEEDING D1',
    'CORSE SEEDING D2'
  ],
  [Area.HBF_C]: [
    'SECTION:OPERAÇÃO HBF',
    'Feed rate HBF (m³/h)',
    'Pressão negativa (Kpa)',
    'SECTION:OPERAÇÃO COLUNAS',
    'ALIMENTANDO COLUNAS?',
    'Feed rate Colunas (m³/h)',
    'SECTION:COLECTOR',
    'Vazão (L/min)',
    'SP (L/min)',
    'SECTION:FROTHER',
    'Vazão (L/min)',
    'SP (L/min)',
    'SECTION:FLOTATION COLUMNS',
    '6C-FC-101',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    '6C-FC-102',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    '6C-FC-201',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    '6C-FC-202',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    '6C-FC-301',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    '6C-FC-302',
    '- Ar (Kpa)',
    '- Nível (%)',
    '- Setpoint (%)',
    'SECTION:EQUIPAMENTOS HBF',
    '6C-VF-101',
    '- Sprays',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6C-VF-201',
    '- Sprays',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6C-VF-301',
    '- Sprays',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    'SECTION:VELOCIDADES DOS BELTS',
    'Velocidade 101 (%)',
    'Velocidade 201 (%)',
    'Velocidade 301 (%)',
    'SECTION:SISTEMAS AUXILIARES',
    'Retorno do tanque 104',
    'VALVULA DE DILUICAO',
    'CORSE SEEDING C1',
    'CORSE SEEDING C2'
  ]
};
